export const BOARDS_REQUEST = 'BOARDS_REQUEST';
export const BOARDS_ADDED = 'BOARDS_ADDED';
export const BOARDS_FAIL = 'BOARDS_FAIL';
export const BOARDS_EDITED = 'BOARDS_EDITED';
export const BOARDS_DELETED = 'BOARDS_DELETED';
export const BOARDS_GET = 'BOARDS_GET';
export const BOARDS_TASK_ADDED = 'BOARDS_TASK_ADDED';
export const BOARDS_TASK_EDITED = 'BOARDS_TASK_EDITED';
